;(function(global){
  var type_string = "";
  var type_int = 0;
  var type_bool = false;
  var type_any = null;
  var type_any2 = "This should be fine!";
  console.log(type_any);
  console.log(type_any2);
  console.log(type_string);
  type_string = "now it has a non-default value";
  console.log(type_string);
  var type_string_initialized = "what";
  var type_string_null_initialized = null;
  var type_int_null_initialized = null;
  var type_bool_null_initialized = null;
  var type_string_not_initialized = null;
  var type_int_not_initialized = null;
  var type_bool_not_initialized = null;
  console.log(type_string_not_initialized);
  console.log(type_int_not_initialized);
  type_int_not_initialized = 1000;
  console.log(type_int_not_initialized);
  var message = "Hello World";
  var age = 35;
  var isSuccess = true;
  console.log(message);
  console.log(age);
  console.log(isSuccess);
}(this));